language: node_js
node_js:
  - '9'
  - '8'
  - '6'
notifications:
  email: false
script:
  - yarn run verify
  - yarn test
  - codecov
cache: yarn
after_success:
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
